<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="1" ignored="1" total="7" passed="2" failed="2" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-06-11T18:42:41 IST" name="Suite" finished-at="2024-06-11T18:43:17 IST" duration-ms="36677">
    <groups>
      <group name="Purchase">
        <method signature="SubmitOrderTest.submitOrder(java.util.HashMap)[pri:0, instance:standAlone_Test.SubmitOrderTest@2b76ff4e]" name="submitOrder" class="standAlone_Test.SubmitOrderTest"/>
      </group> <!-- Purchase -->
      <group name="ErrorHandlying">
        <method signature="ErrorValidationTest.loginErrorValidation()[pri:0, instance:standAlone_Test.ErrorValidationTest@4c51cf28]" name="loginErrorValidation" class="standAlone_Test.ErrorValidationTest"/>
      </group> <!-- ErrorHandlying -->
    </groups>
    <test started-at="2024-06-11T18:42:41 IST" name="Submit Order Test" finished-at="2024-06-11T18:43:16 IST" duration-ms="35498">
      <class name="standAlone_Test.SubmitOrderTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:standAlone_Test.SubmitOrderTest@2b76ff4e]" started-at="2024-06-11T18:42:41 IST" name="launchApplication" finished-at="2024-06-11T18:42:57 IST" duration-ms="16321" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:standAlone_Test.SubmitOrderTest@2b76ff4e]" started-at="2024-06-11T18:42:57 IST" name="submitOrder" data-provider="getData" finished-at="2024-06-11T18:43:05 IST" duration-ms="7720" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{email=jaykrishnagupta@gmail.com, productName=ZARA COAT 3, Password=Jaykrishna@1}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:standAlone_Test.SubmitOrderTest@2b76ff4e]" started-at="2024-06-11T18:43:05 IST" name="tearDown" finished-at="2024-06-11T18:43:05 IST" duration-ms="100" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:standAlone_Test.SubmitOrderTest@2b76ff4e]" started-at="2024-06-11T18:43:05 IST" name="launchApplication" finished-at="2024-06-11T18:43:07 IST" duration-ms="1633" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:standAlone_Test.SubmitOrderTest@2b76ff4e]" started-at="2024-06-11T18:43:07 IST" name="submitOrder" data-provider="getData" finished-at="2024-06-11T18:43:16 IST" duration-ms="8817" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{email=jaykrishnagupt@gmail.com, productName=ADIDAS ORIGINAL, Password=Jaykrishna#1}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at standAlone_Test.SubmitOrderTest.submitOrder(SubmitOrderTest.java:31)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:standAlone_Test.SubmitOrderTest@2b76ff4e]" started-at="2024-06-11T18:43:16 IST" name="tearDown" finished-at="2024-06-11T18:43:16 IST" duration-ms="158" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method signature="orderHistoryTest()[pri:0, instance:standAlone_Test.SubmitOrderTest@2b76ff4e]" started-at="2024-06-11T18:43:16 IST" name="orderHistoryTest" finished-at="2024-06-11T18:43:16 IST" depends-on-methods="standAlone_Test.SubmitOrderTest.submitOrder" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method standAlone_Test.SubmitOrderTest.orderHistoryTest() on instance standAlone_Test.SubmitOrderTest@2b76ff4e depends on not successfully finished methods 
[standAlone_Test.SubmitOrderTest.submitOrder() on instance standAlone_Test.SubmitOrderTest@2b76ff4e]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method standAlone_Test.SubmitOrderTest.orderHistoryTest() on instance standAlone_Test.SubmitOrderTest@2b76ff4e depends on not successfully finished methods 
[standAlone_Test.SubmitOrderTest.submitOrder() on instance standAlone_Test.SubmitOrderTest@2b76ff4e]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:156)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- orderHistoryTest -->
      </class> <!-- standAlone_Test.SubmitOrderTest -->
    </test> <!-- Submit Order Test -->
    <test started-at="2024-06-11T18:42:41 IST" name="Error Validation Test" finished-at="2024-06-11T18:43:17 IST" duration-ms="36677">
      <class name="standAlone_Test.ErrorValidationTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:standAlone_Test.ErrorValidationTest@4c51cf28]" started-at="2024-06-11T18:42:41 IST" name="launchApplication" finished-at="2024-06-11T18:42:55 IST" duration-ms="13977" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method retried="true" signature="loginErrorValidation()[pri:0, instance:standAlone_Test.ErrorValidationTest@4c51cf28]" started-at="2024-06-11T18:42:55 IST" name="loginErrorValidation" finished-at="2024-06-11T18:42:56 IST" duration-ms="1263" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password.] but found [Incorrect email or password]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorrect email or password]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at standAlone_Test.ErrorValidationTest.loginErrorValidation(ErrorValidationTest.java:21)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:standAlone_Test.ErrorValidationTest@4c51cf28]" started-at="2024-06-11T18:42:56 IST" name="tearDown" finished-at="2024-06-11T18:42:56 IST" duration-ms="93" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:standAlone_Test.ErrorValidationTest@4c51cf28]" started-at="2024-06-11T18:42:56 IST" name="launchApplication" finished-at="2024-06-11T18:43:04 IST" duration-ms="7815" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="loginErrorValidation()[pri:0, instance:standAlone_Test.ErrorValidationTest@4c51cf28]" started-at="2024-06-11T18:43:04 IST" name="loginErrorValidation" finished-at="2024-06-11T18:43:05 IST" duration-ms="890" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password.] but found [Incorrect email or password]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorrect email or password]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at standAlone_Test.ErrorValidationTest.loginErrorValidation(ErrorValidationTest.java:21)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:248)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:standAlone_Test.ErrorValidationTest@4c51cf28]" started-at="2024-06-11T18:43:05 IST" name="tearDown" finished-at="2024-06-11T18:43:05 IST" duration-ms="136" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:standAlone_Test.ErrorValidationTest@4c51cf28]" started-at="2024-06-11T18:43:06 IST" name="launchApplication" finished-at="2024-06-11T18:43:12 IST" duration-ms="6295" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="productOrderErrorValidation()[pri:0, instance:standAlone_Test.ErrorValidationTest@4c51cf28]" started-at="2024-06-11T18:43:12 IST" name="productOrderErrorValidation" finished-at="2024-06-11T18:43:17 IST" duration-ms="5356" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- productOrderErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:standAlone_Test.ErrorValidationTest@4c51cf28]" started-at="2024-06-11T18:43:17 IST" name="tearDown" finished-at="2024-06-11T18:43:17 IST" duration-ms="75" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- standAlone_Test.ErrorValidationTest -->
    </test> <!-- Error Validation Test -->
  </suite> <!-- Suite -->
</testng-results>
